profile_order_receipt:
    path:     /profile/orders/{orderNumber}/receipt.pdf
    defaults: { _controller: AppBundle\Controller\ProfileController::orderReceiptAction }
    methods:  [ GET ]

profile_order_receipt_generate:
    path:     /profile/orders/{orderNumber}/generate-receipt
    defaults: { _controller: AppBundle\Controller\ProfileController::generateOrderReceiptAction }
    methods:  [ POST ]

profile_order:
    path:     /profile/orders/{id}
    defaults: { _controller: AppBundle\Controller\ProfileController::orderAction }
    methods:  [ GET, POST ]

profile_orders:
    path:     /profile/orders
    defaults:
        _controller: AppBundle\Controller\ProfileController::orderListAction
        layout: 'profile.html.twig'
        template: 'profile/orders.html.twig'
        routes:
            restaurant: restaurant
            order_receipt: profile_order_receipt
            order_receipt_generate: profile_order_receipt_generate
            order: profile_order
    methods:  [ GET ]
